apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master
  labels:
    name: redis-master
spec:
  replicas: 1
  selector:
    name: redis-master
  template:
    metadata:
      labels:
        name: redis-master
    spec:
      containers:
      - name: master
        image: redis
        ports:
          - containerPort: 6379
        volumeMounts:
          # name must match the volume name below
        - name: redis-pd
          # mount path within the container
          mountPath: /data
      volumes:
        - name: redis-pd
          gcePersistentDisk:
        # This GCE PD must already exist.
            pdName: redis-master
            fsType: ext4
